export const metadata = {
  title: 'Terms of Service',
  description: 'The legal agreement between you and AI Toolkit.',
};

export default function TermsPage() {
  const lastUpdated = 'June 20, 2026';

  return (
    <div className="bg-black pt-20 pb-20">
      <div className="mx-auto max-w-4xl px-4 sm:px-6 lg:px-8">
        <h1 className="text-4xl md:text-5xl font-bold text-white mb-4">Terms of Service</h1>
        <p className="text-slate-500 mb-12 italic">Last Updated: {lastUpdated}</p>

        <div className="prose prose-invert prose-indigo max-w-none space-y-12 text-slate-400">
          <section>
            <h2 className="text-2xl font-bold text-white mb-4">1. Acceptance of Terms</h2>
            <p className="leading-relaxed">
              By accessing or using AI Toolkit, you agree to be bound by these Terms of Service and
              all applicable laws and regulations. If you do not agree with any of these terms, you
              are prohibited from using or accessing our tools.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-white mb-4">2. Use License</h2>
            <p className="mb-4">
              We grant you a limited, non-exclusive, non-transferable license to use our AI services
              for personal or professional purposes, subject to the following restrictions:
            </p>
            <ul className="list-disc pl-6 space-y-2">
              <li>You may not use the services for any illegal or unauthorized purpose.</li>
              <li>
                You may not attempt to reverse engineer or extract the source code of our AI models.
              </li>
              <li>
                You may not use automated scripts to "scrape" data from our platform without express
                permission.
              </li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-white mb-4">3. User Responsibility</h2>
            <p className="leading-relaxed">
              You are solely responsible for the content you process through our tools. While our AI
              aims for high accuracy, we do not guarantee that the output is error-free or suitable
              for any specific legal, medical, or professional purpose. Always review AI-generated
              content before publication.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-white mb-4">4. Intellectual Property</h2>
            <p className="leading-relaxed">
              You retain all ownership rights to the original text you input. We claim no ownership
              over the outputs generated by our AI tools. You are free to use, publish, and monetize
              the outputs as you see fit.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-white mb-4">5. Subscription and Payments</h2>
            <p className="leading-relaxed">
              Premium features require a paid subscription. All fees are non-refundable unless
              stated otherwise in our refund policy. We reserve the right to change our pricing upon
              30 days' notice.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-white mb-4">6. Limitation of Liability</h2>
            <p className="leading-relaxed">
              AI Toolkit shall not be liable for any indirect, incidental, or consequential damages
              resulting from the use or inability to use our services. Our maximum liability shall
              not exceed the amount paid by you in the 12 months preceding the claim.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-white mb-4">7. Governing Law</h2>
            <p className="leading-relaxed">
              These terms are governed by and construed in accordance with the laws of the
              jurisdiction in which AI Toolkit Inc. is headquartered, without regard to its conflict
              of law provisions.
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
